<html ng-app>
<head>
    <title>All The Satoshi!</title>
    <link href="style.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js" type="application/javascript"></script>
    <script src="js/controller.js" type="application/javascript"></script>
</head>
<body>
<div class="header" ng-controller="">
    <div class="logo">All The Satoshi!</div>
    <div class="ad">
        <iframe scrolling="no" frameborder="0" src="//adbit.co/adspace.php?a=1F4DU7F5AB57A" style="overflow:hidden;width:728px;height:90px;"></iframe>
    </div>
</div>
<div class="content">
    <div class="ad left"></div>
    <div class="ad right"></div>
    <div class="middle left">