<div class="middle left">
    <h1>Welcome to All The Satoshi Beta Faucet.</h1>
    <div class="ad large-rectangle" style="margin: 0 auto;"><?php AdManager::insert('a-ads','69468'); ?></div><br>
    <form method="post" action="./cgi-bin/login.php">
        <label for="bitcoin-address">Your BitCoin Address: </label>
        <input id="bitcoin-address" type="text" name="btcAddress"/>
        <input type="submit" value="Login!"/>
    </form>
    <div class="ad banner" style="margin: 0 auto;"><?php AdManager::insert('bitclix','11724'); ?></div>
</div>